[package]
name = "algoritmos"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "l03-A"
path = "src/l03.rs"

[[bin]]
name = "l03-B"
path = "src/l03B.rs"

[dependencies]
rand = "0.9.1"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
